title: "{{Issue Description}} | {{your GitHub username}}"
body:
- type: input
  attributes:
    label: Link to debugging doc
    description: "Please paste the Google Doc link to the debugging doc here."
  validations:
    required: true
- type: checkboxes
  id: sharing
  attributes:
    label: "Please confirm the following:"
    options:
    - label: "I confirm that I've given edit access to the doc to the dev mailing lists, as described in the instructions at the top of the doc."
      required: true
    - label: "I confirm that I set the sharing options of the doc to 'anyone with the link can comment'."
      required: true
